import { useState } from 'react';
import { Link, router } from 'expo-router';
import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/Screen';
import { BrandMark } from '@/components/BrandMark';
import { FormField } from '@/components/FormField';
import { AppButton } from '@/components/AppButton';
import { colors, radius } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { errorMessage } from '@/hooks/useErrorMessage';
import { appConfig } from '@/services/config';
export default function RegisterScreen() { const { register } = useAuth(); const [displayName, setName] = useState(''); const [birthDate, setBirthDate] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [accepted, setAccepted] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async () => { if (!accepted) return setError('You must accept the safety rules, terms, and privacy policy.'); setError(''); setLoading(true); try { await register({ displayName: displayName.trim(), birthDate, email: email.trim(), password, acceptedTerms: true }); router.replace('/(tabs)/discover'); } catch (e) { setError(errorMessage(e)); } finally { setLoading(false); } }; return <Screen keyboard><BrandMark/><View style={styles.card}><Text style={styles.title}>Start with a real spark</Text><Text style={styles.copy}>Adults only. Every account starts with 25 Sparks.</Text><FormField label="First name" value={displayName} onChangeText={setName} autoComplete="name"/><FormField label="Birth date (YYYY-MM-DD)" value={birthDate} onChangeText={setBirthDate} placeholder="1990-08-24" keyboardType="numbers-and-punctuation"/><FormField label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><FormField label="Password (10+ characters)" value={password} onChangeText={setPassword} secureTextEntry/><Pressable onPress={() => setAccepted(v => !v)} style={styles.checkRow}><Ionicons name={accepted ? 'checkbox' : 'square-outline'} size={24} color={accepted ? colors.gold : colors.muted}/><Text style={styles.checkText}>I’m 18 or older and agree to the zero-tolerance safety rules.</Text></Pressable><View style={styles.legalRow}><Text onPress={() => Linking.openURL(appConfig.termsUrl)} style={styles.link}>Terms of Service</Text><Text style={styles.dot}>•</Text><Text onPress={() => Linking.openURL(appConfig.privacyUrl)} style={styles.link}>Privacy Policy</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}<AppButton title="Create my account" loading={loading} onPress={submit}/><Text style={styles.footer}>Already have an account? <Link href="/(auth)/login" style={styles.link}>Sign in</Link></Text></View></Screen>; }
const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, padding: 22, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, gap: 14 }, title: { color: colors.text, fontSize: 26, fontWeight: '900' }, copy: { color: colors.muted }, checkRow: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' }, checkText: { color: colors.cream, lineHeight: 19, flex: 1 }, error: { color: colors.red }, footer: { color: colors.muted, textAlign: 'center' }, legalRow: { flexDirection: 'row', justifyContent: 'center', gap: 8 }, dot: { color: colors.muted }, link: { color: colors.gold, fontWeight: '800' } });
