import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/Screen';
import { BrandMark } from '@/components/BrandMark';
import { ProfileCard } from '@/components/ProfileCard';
import { EmptyView } from '@/components/StateView';
import { api } from '@/services/api';
import { appConfig } from '@/services/config';
import { demoProfiles } from '@/services/demo';
import type { Profile } from '@/types/models';
import { colors, radius, shadow } from '@/constants/theme';
import { errorMessage } from '@/hooks/useErrorMessage';
export default function DiscoverScreen() { const [items, setItems] = useState<Profile[]>(demoProfiles); const [index, setIndex] = useState(0); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); useEffect(() => { if (!appConfig.demoMode) api<{ profiles: Profile[] }>('/discover/').then(d => setItems(d.profiles)).catch(e => setNotice(errorMessage(e))); }, []); const profile = items[index]; const choose = async (decision: 'pass'|'spark'|'super_spark') => { if (!profile || busy) return; setBusy(true); try { if (!appConfig.demoMode) await api('/discover/swipe', { method: 'POST', body: JSON.stringify({ targetUserId: profile.id, decision }) }); setNotice(decision === 'pass' ? 'Passed with kindness' : decision === 'spark' ? 'Spark sent' : 'Super Spark sent for 5 Sparks'); setIndex(v => v + 1); } catch (e) { setNotice(errorMessage(e)); } finally { setBusy(false); } }; return <Screen><BrandMark/><View style={styles.note}><Ionicons name="sparkles" color={colors.gold} size={15}/><Text style={styles.noteText}>{Math.max(items.length - index, 0)} intentional introductions today</Text></View>{profile ? <><ProfileCard profile={profile}/><View style={styles.actions}><Action icon="close" label="Pass" onPress={() => choose('pass')} disabled={busy}/><Pressable disabled={busy} onPress={() => choose('spark')} style={({ pressed }) => [styles.ignite, pressed && styles.pressed]}><Ionicons name="flame" size={32} color="#2A1204"/><Text style={styles.igniteText}>IGNITE{`\n`}THE SPARK</Text></Pressable><Action icon="gift" label="Super Spark" onPress={() => choose('super_spark')} disabled={busy}/></View><Text style={styles.ethics}>No endless swiping. A small new set arrives each day.</Text></> : <EmptyView title="Your candle is resting" message="You’ve seen today’s introductions. A small new set will arrive tomorrow."/>}{notice ? <View style={styles.toast}><Text style={styles.toastText}>{notice}</Text></View> : null}</Screen>; }
function Action({ icon, label, onPress, disabled }: { icon: keyof typeof Ionicons.glyphMap; label: string; onPress: () => void; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><Ionicons name={icon} size={26} color={colors.goldBright}/><Text style={styles.actionText}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ note: { alignSelf: 'center', flexDirection: 'row', gap: 7, alignItems: 'center', backgroundColor: '#24160C', borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: 14, paddingVertical: 8 }, noteText: { color: colors.cream, fontSize: 12 }, actions: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingVertical: 10 }, action: { width: 88, height: 88, borderRadius: 44, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceAlt, alignItems: 'center', justifyContent: 'center', gap: 4, ...shadow }, actionText: { color: colors.cream, fontSize: 11, textAlign: 'center' }, ignite: { width: 128, height: 128, borderRadius: 64, backgroundColor: colors.gold, borderWidth: 4, borderColor: colors.goldBright, alignItems: 'center', justifyContent: 'center', ...shadow }, igniteText: { color: '#2A1204', fontWeight: '900', fontSize: 15, textAlign: 'center' }, pressed: { opacity: .72, transform: [{ scale: .97 }] }, ethics: { color: colors.muted, textAlign: 'center', fontSize: 12 }, toast: { position: 'absolute', left: 40, right: 40, bottom: 100, backgroundColor: '#2A1B10', borderColor: colors.gold, borderWidth: 1, borderRadius: radius.pill, padding: 12 }, toastText: { color: colors.text, textAlign: 'center', fontWeight: '700' } });
