import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/Screen';
import { BrandMark } from '@/components/BrandMark';
import { Avatar } from '@/components/Avatar';
import { EmptyView } from '@/components/StateView';
import { api } from '@/services/api';
import { appConfig } from '@/services/config';
import { demoMatches } from '@/services/demo';
import type { Match } from '@/types/models';
import { colors, radius } from '@/constants/theme';
export default function MatchesScreen() { const [matches, setMatches] = useState<Match[]>(demoMatches); useEffect(() => { if (!appConfig.demoMode) api<{ matches: Match[] }>('/discover/matches').then(d => setMatches(d.matches)).catch(() => setMatches([])); }, []); return <Screen><View style={styles.heading}><BrandMark compact/><View><Text style={styles.small}>Your connections</Text><Text style={styles.title}>Matches</Text></View></View><View style={styles.banner}><Ionicons name="flame" size={21} color={colors.gold}/><Text style={styles.bannerText}>Every match starts with one shared question, not a blank “hey.”</Text></View>{matches.length ? matches.map(match => { const free = Math.max(0, match.freeMessageLimit - match.messageCount); return <Pressable key={match.id} onPress={() => router.push({ pathname: '/messages/[conversationId]', params: { conversationId: match.conversationId, userId: match.userId, displayName: match.displayName } })} style={styles.row}><Avatar name={match.displayName} uri={match.photoUrl}/><View style={styles.meta}><View style={styles.nameRow}><Text style={styles.name}>{match.displayName}</Text>{match.verified && <Ionicons name="checkmark-circle" size={16} color={colors.blue}/>}</View><Text style={styles.note}>{match.journeyStage ? `Stage: ${match.journeyStage.replaceAll('_', ' ')}` : match.unlockedAt ? 'Your candle is lit' : `${free} free messages left`}</Text></View><Ionicons name={match.unlockedAt ? 'flame' : 'chatbubble-outline'} color={match.unlockedAt ? colors.gold : colors.muted} size={23}/></Pressable>; }) : <EmptyView title="No matches yet" message="Send a thoughtful Spark when someone stands out."/>}</Screen>; }
const styles = StyleSheet.create({ heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, small: { color: colors.muted, fontSize: 11, textTransform: 'uppercase' }, title: { color: colors.text, fontSize: 28, fontWeight: '900' }, banner: { flexDirection: 'row', gap: 10, padding: 14, borderRadius: radius.md, backgroundColor: '#21150D', borderWidth: 1, borderColor: colors.border }, bannerText: { color: colors.cream, flex: 1, lineHeight: 19 }, row: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 13, padding: 12, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderSoft }, meta: { flex: 1, gap: 5 }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: 5 }, name: { color: colors.text, fontSize: 17, fontWeight: '800' }, note: { color: colors.muted, fontSize: 13 } });
