import { useState } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/Screen';
import { FormField } from '@/components/FormField';
import { AppButton } from '@/components/AppButton';
import { colors, radius } from '@/constants/theme';
import { api } from '@/services/api';
import { appConfig } from '@/services/config';
import { errorMessage } from '@/hooks/useErrorMessage';
export default function SafetyScreen() { const params = useLocalSearchParams<{ userId?: string; conversationId?: string }>(); const [userId, setUserId] = useState(params.userId ?? ''); const [details, setDetails] = useState(''); const [notice, setNotice] = useState(''); const act = async (kind: 'block'|'report') => { setNotice(''); try { if (!appConfig.demoMode) await api(`/safety/${kind}`, { method: 'POST', body: JSON.stringify(kind === 'block' ? { userId } : { userId, conversationId: params.conversationId || undefined, category: 'other', details }) }); setNotice(kind === 'block' ? 'User blocked. They can no longer contact you.' : 'Report received. Our safety team can review it.'); } catch (e) { setNotice(errorMessage(e)); } }; return <Screen><View style={styles.hero}><Ionicons name="shield-checkmark" color={colors.green} size={42}/><Text style={styles.title}>Safe, decent, and respectful</Text><Text style={styles.copy}>Candle Love filters profanity, threats, scams, outside payment requests, contact sharing from new accounts, and repeated spam.</Text></View><Text style={styles.section}>Report or block</Text><FormField label="User ID" value={userId} onChangeText={setUserId} placeholder="Paste the account ID"/><FormField label="What happened?" value={details} onChangeText={setDetails} multiline placeholder="Do not include passwords or payment details."/><AppButton title="Submit report" onPress={() => act('report')}/><AppButton title="Block this user" kind="danger" onPress={() => act('block')}/>{notice ? <Text style={styles.notice}>{notice}</Text> : null}<View style={styles.rules}>{['No harassment, hate, threats, or sexual pressure.', 'No requests for gift cards, crypto, wire transfers, or outside payments.', 'No impersonation or fake identity claims.', 'No minors. Report any underage concern immediately.', 'Meet in public and tell someone where you are going.'].map(rule => <View key={rule} style={styles.rule}><Ionicons name="checkmark-circle" color={colors.green} size={18}/><Text style={styles.ruleText}>{rule}</Text></View>)}</View></Screen>; }
const styles = StyleSheet.create({ hero: { alignItems: 'center', gap: 10, padding: 20, backgroundColor: colors.greenBg, borderWidth: 1, borderColor: '#285B3C', borderRadius: radius.lg }, title: { color: colors.text, fontSize: 23, fontWeight: '900', textAlign: 'center' }, copy: { color: '#C2DAC9', textAlign: 'center', lineHeight: 20 }, section: { color: colors.text, fontSize: 18, fontWeight: '900' }, notice: { color: colors.goldBright, textAlign: 'center' }, rules: { gap: 12, padding: 15, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.borderSoft }, rule: { flexDirection: 'row', gap: 9, alignItems: 'flex-start' }, ruleText: { color: colors.cream, lineHeight: 19, flex: 1 } });
