import { useEffect, useState } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import * as Linking from 'expo-linking';
import { Screen } from '@/components/Screen';
import { AppButton } from '@/components/AppButton';
import { colors, radius } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { api } from '@/services/api';
import { appConfig } from '@/services/config';
import { configurePurchases, getPurchasePacks, buyPack, type PurchasePack } from '@/services/purchases';
import { errorMessage } from '@/hooks/useErrorMessage';
const webPacks: PurchasePack[] = [{ id: 'glow', title: 'Glow Pack', description: '50 Sparks', price: '$4.99', tokens: 50 }, { id: 'flame', title: 'Flame Pack', description: '140 Sparks', price: '$9.99', tokens: 140 }, { id: 'bonfire', title: 'Bonfire Pack', description: '320 Sparks', price: '$19.99', tokens: 320 }];
export default function WalletScreen() { const { user, refreshUser } = useAuth(); const [packs, setPacks] = useState<PurchasePack[]>(webPacks); const [error, setError] = useState(''); const [busy, setBusy] = useState(''); useEffect(() => { if (Platform.OS !== 'web' && user && appConfig.enablePayments) configurePurchases(user.id).then(getPurchasePacks).then(rows => rows.length && setPacks(rows)).catch(e => setError(errorMessage(e))); }, [user]); const purchase = async (pack: PurchasePack) => { if (!appConfig.enablePayments) return setError('Payments are disabled until App Store and Stripe products are configured.'); setBusy(pack.id); setError(''); try { if (Platform.OS === 'web') { const data = await api<{ url: string }>('/wallet/checkout', { method: 'POST', body: JSON.stringify({ packId: pack.id, returnUrl: Linking.createURL('/wallet') }) }); await WebBrowser.openBrowserAsync(data.url); } else { await buyPack(pack.id); } await refreshUser(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(''); } }; return <Screen><Text style={styles.title}>Spark Wallet</Text><View style={styles.balance}><Text style={styles.balanceLabel}>Available balance</Text><Text style={styles.balanceValue}>{user?.sparkBalance ?? 0}</Text><Text style={styles.balanceUnit}>Sparks</Text></View><Text style={styles.section}>Choose a pack</Text>{packs.map(pack => <View key={pack.id} style={styles.pack}><View style={{ flex: 1 }}><Text style={styles.packTitle}>{pack.title}</Text><Text style={styles.packCopy}>{pack.description || `${pack.tokens} Sparks`}</Text></View><Text style={styles.price}>{pack.price}</Text><AppButton title="Buy" loading={busy === pack.id} onPress={() => purchase(pack)}/></View>)}{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.info}><Text style={styles.infoTitle}>Fair-use promise</Text><Text style={styles.infoText}>Sparks unlock chat once, send Super Sparks, and send gifts. Regular unlocked messages never cost per message. iOS purchases use Apple In-App Purchase through RevenueCat; web purchases use Stripe.</Text></View></Screen>; }
const styles = StyleSheet.create({ title: { color: colors.text, fontSize: 30, fontWeight: '900' }, balance: { alignItems: 'center', padding: 24, backgroundColor: '#2B1809', borderWidth: 1, borderColor: colors.goldDark, borderRadius: radius.lg }, balanceLabel: { color: colors.muted }, balanceValue: { color: colors.goldBright, fontSize: 56, fontWeight: '900' }, balanceUnit: { color: colors.gold, fontWeight: '800' }, section: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 6 }, pack: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: radius.md }, packTitle: { color: colors.text, fontWeight: '900' }, packCopy: { color: colors.muted, marginTop: 3 }, price: { color: colors.goldBright, fontWeight: '900' }, error: { color: colors.red, textAlign: 'center' }, info: { padding: 15, borderRadius: radius.md, backgroundColor: colors.greenBg, borderWidth: 1, borderColor: '#285B3C' }, infoTitle: { color: colors.green, fontWeight: '900' }, infoText: { color: '#BBD6C4', marginTop: 5, lineHeight: 19 } });
